site_name: RRHQD Wiki
site_url: https://runesrepohub.github.io/RRHQD/
repo_name: RRHQD
repo_url: https://github.com/RunesRepoHub/RRHQD
edit_uri: https://github.com/RunesRepoHub/RRHQD/edit/Dev/Docs/
use_directory_urls: false
nav:
    - RRHQD Documentation:
      - Getting Started With RRHQD:
        - What is RRHQD?: 'index.md'
        - Requirements RRHQD: 'MkDocs/RRHQD/Readme/Requirements.md'
        - How to Install RRHQD: 'MkDocs/RRHQD/Readme/Installation.md'
        - Main Menu RRHQD: 'MkDocs/RRHQD/Readme/Main-Menu.md'
        - Docker Support RRHQD: 'MkDocs/RRHQD/Readme/Docker-Support.md'
        - Install Other RRH Software: 'MkDocs/RRHQD/Readme/RunesRepoHub.md'
        - Cronjobs: 'MkDocs/RRHQD/Readme/Cronjob.md'
        - Youtube Scripts: 'MkDocs/RRHQD/Readme/Youtube-Scripts.md'
        - Quick Installers: 'MkDocs/RRHQD/Readme/Quick-Installer.md'
        - Quick Tools: 'MkDocs/RRHQD/Readme/Quick-Tools.md'
        - Docker CnC: 'MkDocs/RRHQD/Readme/Docker-CnC.md'
      - Configuration Guides:
        - Docker Configuration Guides:
          - Setup a Linkwarden Docker: 'MkDocs/RRHQD/Setup-Linkwarden.md'
          - Setup a Deluge Docker: 'MkDocs/RRHQD/Setup-Deluge.md'
          - Setup a Checkmk Docker: 'MkDocs/RRHQD/Setup-Checkmk.md'
          - Setup a Cloudflare Tunnel Docker: 'MkDocs/RRHQD/Setup-Cloudflare.md'
          - Setup a Ghost Docker: 'MkDocs/RRHQD/Setup-Ghost.md'
          - Setup a It-tools Docker: 'MkDocs/RRHQD/Setup-It-tools.md'
          - Setup a Jackett Docker: 'MkDocs/RRHQD/Setup-Jackett.md'
          - Setup a Llama-GPT Docker: 'MkDocs/RRHQD/Setup-Llama-GPT.md'
          - Setup a MediaCMS Docker: 'MkDocs/RRHQD/Setup-MediaCMS.md'
          - Setup a Memos Docker: 'MkDocs/RRHQD/Setup-Memos.md'
          - Setup a MySQL Docker: 'MkDocs/RRHQD/Setup-MySQL.md'
          - Setup a N8N Docker: 'MkDocs/RRHQD/Setup-N8N.md'
          - Setup a NTFY Docker: 'MkDocs/RRHQD/Setup-NTFY.md'
          - Setup a Ombi Docker: 'MkDocs/RRHQD/Setup-Ombi.md'
          - Setup a Portainer Docker: 'MkDocs/RRHQD/Setup-Portainer.md'
          - Setup a Postgres Docker: 'MkDocs/RRHQD/Setup-Postgres.md'
          - Setup a Radarr Docker: 'MkDocs/RRHQD/Setup-Radarr.md'
          - Setup a Sonarr Docker: 'MkDocs/RRHQD/Setup-Sonarr.md'
          - Setup a Uptime-Kuma Docker: 'MkDocs/RRHQD/Setup-Uptime-Kuma.md'
          - Setup a Vaultwarden Docker: 'MkDocs/RRHQD/Setup-Vaultwarden.md'
    - ACS Documentation:
      - Getting Started With ACS:
        - What is ACS?: 'MkDocs/ACS/ACS-index.md'
        - Requirements ACS: 'MkDocs/ACS/ACS-requirement.md'
        - How to Install ACS: 'MkDocs/ACS/ACS-install.md'
      - Understand The Source Code:
        - Description of Source Code ACS: 'MkDocs/ACS/ACS-source.md'
    - RP-Helpdesk Docs: 'https://runesrepohub.github.io/RPH-Docs/index.html'
theme:
  icon:
      logo: fontawesome/brands/gitkraken
      repo: fontawesome/brands/gitkraken
      admonition:
        note: material/notebook-edit
        abstract: material/file-edit
        info: material/notebook-check
        tip: material/tooltip-check-outline
        success: simple/riseup
        question: octicons/question-16
        warning: fontawesome/solid/person-military-pointing
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: material/docker
        example: material/monitor-edit
        quote: octicons/quote-16
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: black
      accent: indigo

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: indigo

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: black
      accent: indigo
  features:
    # - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search
copyright: Copyright &copy; 2023 RP-Helpdesk 
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
extra:
  analytics:
    provider: google
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/christian-rune


