name: Set up protected branch on prod

on:
  push:
    branches:
      - Prod
      - Dev

jobs:
  set-up-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Branch Protection
        uses: peter-evans/create-or-update-branch-protection@v4.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          branch: prod
          enforce_admins: true
          required_pull_request_reviews:
            dismiss_stale_reviews: true
            require_code_owner_reviews: true
            required_approving_review_count: 1
          required_status_checks:
            strict: true
            contexts:
              - CI
