name: Bug Branch Creation

on:
  issues:
    types: [ labeled ]

jobs:
  create-backup-branch:
    if: contains(github.event.issue.labels.*.name, 'bug')
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a new branch based on the Dev branch
        run: |
          git checkout Dev
          git checkout -b "Bug-Branch-${GITHUB_RUN_NUMBER}"
          git push --set-upstream origin "Bug-Branch-${GITHUB_RUN_NUMBER}"

  update-issue:
    if: contains(github.event.issue.labels.*.name, 'bug')
    runs-on: self-hosted
    permissions:
      issues: write
    steps:
      - name: Update the GitHub issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Automated Bug Branch: https://github.com/RunesRepoHub/RRHQD/tree/Bug-Branch-${{ github.run_number }}

  create-pr:
    if: contains(github.event.issue.labels.*.name, 'bug')
    runs-on: self-hosted
    needs: [create-backup-branch]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Bug Fix for Issue #${{ github.event.issue.number }}"
          body: "This branch fixes Issue #${{ github.event.issue.number }}"
          branch: Bug-Branch-${{ github.run_number }}
          base: Dev

  link-pr:
    if: contains(github.event.issue.labels.*.name, 'bug')
    runs-on: self-hosted
    needs: [create-pr]
    permissions:
      issues: write
    steps:
      - name: Link PR on issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Automated Bug Branch: https://github.com/RunesRepoHub/RRHQD/pull/${{ github.event.number }}"

