name: Merge Bot

on:
  pull_request:
    types:
      - ready_for_review
  pull_request_review:
    types:
      - dismissed
      - submitted

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.4.5
      with:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        test: false
        reviewers: true
        labels: ready, merge
        blocking_labels: do not merge
        checks_enabled: true
        method: merge
        delete_source_branch: false