name: PR Branch Creation

on:
  push:
    branches:
      - Dev

jobs:
  create-pr-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a new branch based on the Dev branch
        run: |
          git checkout Dev
          git checkout -b "PR-${GITHUB_RUN_NUMBER}"
          git push --set-upstream origin "PR-${GITHUB_RUN_NUMBER}"


